ISSI_BATCHES = [
    # BATCH 1
    [
        "AALI.JK","ABBA.JK","ACES.JK","ACST.JK","ADES.JK","ADHI.JK","ADMG.JK","ADRO.JK","AGAR.JK","AGII.JK",
        "AKKU.JK","AKPI.JK","AKRA.JK","AKSI.JK","ALDO.JK","ALKA.JK","ALMI.JK","AMAG.JK","AMFG.JK","AMRT.JK",
        "ANDI.JK","ANTM.JK","APEX.JK","APIC.JK","ARCI.JK","ARKA.JK","ARNA.JK","ARTA.JK","ARTI.JK","ASBI.JK",
        "ASDM.JK","ASGR.JK","ASII.JK","ASMI.JK","ASRI.JK","ATIC.JK","AUTO.JK","BABP.JK","BACA.JK","BAJA.JK",
        "BBHI.JK","BBKP.JK","BBMD.JK","BBYB.JK","BCIC.JK","BEBS.JK","BEEF.JK","BELL.JK","BFIN.JK","BHAT.JK",
        "BIMA.JK","BINA.JK","BIPI.JK","BIRD.JK","BJBR.JK","BJTM.JK","BKSL.JK","BMAS.JK","BNBA.JK","BNGA.JK",
        "BOGA.JK","BOLA.JK","BRIS.JK","BRMS.JK","BRPT.JK","BSDE.JK","BSML.JK","BUKA.JK","BULL.JK","BWPT.JK",
        "CAMP.JK","CARE.JK","CASA.JK","CBMF.JK","CEKA.JK","CENT.JK","CFIN.JK","CINT.JK","CLAY.JK","CMNP.JK",
        "CNKO.JK","CNTX.JK","CPIN.JK","COWL.JK","CSAP.JK","CTRA.JK","DART.JK","DEAL.JK","DEFI.JK","DGNS.JK"
    ],
    # BATCH 2
    [
        "DIGI.JK","DILD.JK","DKFT.JK","DLTA.JK","DMND.JK","DOID.JK","DPNS.JK","DSFI.JK","DSSA.JK","DUTI.JK",
        "DVLA.JK","DWGL.JK","DYAN.JK","ECII.JK","EKAD.JK","ELSA.JK","ELTY.JK","EMDE.JK","ENRG.JK","ENVY.JK",
        "EPAC.JK","ERAA.JK","ESIP.JK","ESSA.JK","ESTA.JK","ETWA.JK","EXCL.JK","FAST.JK","FASW.JK","FILM.JK",
        "FIRE.JK","FISH.JK","FITT.JK","FMII.JK","FOOD.JK","FORU.JK","FREN.JK","FUJI.JK","GAMA.JK","GDST.JK",
        "GEMA.JK","GEMS.JK","GGRM.JK","GIAA.JK","GJTL.JK","GLOB.JK","GLVA.JK","GMFI.JK","GMTD.JK","GOTO.JK",
        "GPRA.JK","GRHA.JK","GSMF.JK","GTBO.JK","GWSA.JK","HADE.JK","HAIS.JK","HATM.JK","HDTX.JK","HERO.JK",
        "HEXA.JK","HITS.JK","HKMU.JK","HMSP.JK","HOKI.JK","HOME.JK","HOMI.JK","HOTL.JK","HRTA.JK","HRUM.JK",
        "IATA.JK","IBFN.JK","IBST.JK","ICBP.JK","ICON.JK","IDPR.JK","IFII.JK","IFSH.JK","IGAR.JK","IIKP.JK",
        "IKAI.JK","IKAN.JK","IKBI.JK","IMAS.JK","IMPC.JK","INAF.JK","INAI.JK","INCF.JK","INCI.JK","INCO.JK"
    ],
    # BATCH 3
    [
        "INDF.JK","INDY.JK","INET.JK","INKP.JK","INOV.JK","INPC.JK","INPP.JK","INPS.JK","INRU.JK","INTA.JK",
        "INTD.JK","INTP.JK","IPCC.JK","IPCM.JK","IPOL.JK","IPTV.JK","IRRA.JK","ISAT.JK","ISSP.JK","ITIC.JK",
        "ITMA.JK","ITMG.JK","JARR.JK","JAST.JK","JAWA.JK","JAYA.JK","JECC.JK","JGLE.JK","JIHD.JK","JKON.JK",
        "JKSW.JK","JMAS.JK","JPFA.JK","JRPT.JK","JSMR.JK","JSPT.JK","JTPE.JK","KAEF.JK","KARW.JK","KAYU.JK",
        "KBAG.JK","KBLI.JK","KBLM.JK","KDSI.JK","KEEN.JK","KEJU.JK","KIJA.JK","KINO.JK","KJEN.JK","KKGI.JK",
        "KLBF.JK","KMDS.JK","KMTR.JK","KOBX.JK","KOIN.JK","KONI.JK","KOPI.JK","KOTA.JK","KPAL.JK","KPAS.JK",
        "KPIG.JK","KRAH.JK","KRAS.JK","KREN.JK","LAND.JK","LAPD.JK","LEAD.JK","LIFE.JK","LINK.JK","LION.JK",
        "LMAS.JK","LMPI.JK","LMSH.JK","LPCK.JK","LPLI.JK","LPKR.JK","LPPF.JK","LRNA.JK","LSIP.JK","LTLS.JK",
        "LUCY.JK","MABA.JK","MAGP.JK","MAIN.JK","MAYA.JK","MBAP.JK","MBSS.JK","MBTO.JK","MCAS.JK","MCOL.JK"
    ],
    # BATCH 4
    [
        "MDIA.JK","MDKA.JK","MDLN.JK","MEDC.JK","MEGA.JK","MERK.JK","META.JK","MFMI.JK","MGLV.JK","MGNA.JK",
        "MGRO.JK","MICE.JK","MIDI.JK","MIKA.JK","MINA.JK","MIRA.JK","MITI.JK","MKNT.JK","MKPI.JK","MLBI.JK",
        "MLIA.JK","MLPL.JK","MLPT.JK","MMLP.JK","MNCN.JK","MOLI.JK","MPMX.JK","MPOW.JK","MPPA.JK","MPRO.JK",
        "MRAT.JK","MREI.JK","MSIN.JK","MSKY.JK","MTDL.JK","MTEL.JK","MTFN.JK","MTLA.JK","MTPS.JK","MTRA.JK",
        "MTWI.JK","MYOR.JK","MYRX.JK","MYTX.JK","NASA.JK","NATO.JK","NELY.JK","NFCX.JK","NICK.JK","NIKL.JK",
        "NIPS.JK","NIRO.JK","NISP.JK","NOBU.JK","NPGF.JK","NRCA.JK","NUSA.JK","NZIA.JK","OASA.JK","OCAP.JK",
        "OKAS.JK","OMRE.JK","OPMS.JK","PADI.JK","PALM.JK","PANS.JK","PBRX.JK","PBSA.JK","PCAR.JK","PDES.JK",
        "PEGE.JK","PEHA.JK","PGAS.JK","PGJO.JK","PGLI.JK","PGRM.JK","PICO.JK","PJAA.JK","PKPK.JK","PLAS.JK",
        "PLIN.JK","PNBN.JK","PNBS.JK","PNGO.JK","PNIN.JK","PNLF.JK","PNSE.JK","POLA.JK","POLI.JK","POLU.JK"
    ],
    # BATCH 5
    [
        "POLL.JK","POLY.JK","POOL.JK","PORT.JK","POWR.JK","PPGL.JK","PPRE.JK","PPRO.JK","PRAS.JK","PRAY.JK",
        "PRDA.JK","PRIM.JK","PSAB.JK","PSDN.JK","PSGO.JK","PSKT.JK","PSSI.JK","PTBA.JK","PTDU.JK","PTIS.JK",
        "PTPP.JK","PTPW.JK","PTRO.JK","PTSN.JK","PTSP.JK","PUDP.JK","PURA.JK","PURE.JK","PURI.JK","PWON.JK",
        "PYFA.JK","RAJA.JK","RALS.JK","RANC.JK","RDTX.JK","REAL.JK","RELI.JK","RICY.JK","RIGS.JK","RIMO.JK",
        "RISE.JK","RMBA.JK","ROCK.JK","RODA.JK","ROTI.JK","RUIS.JK","SAFE.JK","SAME.JK","SAMF.JK","SAPX.JK",
        "SATU.JK","SBAT.JK","SCCO.JK","SCMA.JK","SCNP.JK","SCPI.JK","SDMU.JK","SDPC.JK","SDRA.JK","SFAN.JK",
        "SGER.JK","SHID.JK","SHIP.JK","SICO.JK","SIDO.JK","SILO.JK","SIMA.JK","SIMP.JK","SIPD.JK","SKBM.JK",
        "SKLT.JK","SKRN.JK","SKYB.JK","SLIS.JK","SMAR.JK","SMBR.JK","SMCB.JK","SMDR.JK","SMGR.JK","SMKL.JK",
        "SMMA.JK","SMMT.JK","SMRA.JK","SMSM.JK","SOCI.JK","SOFA.JK","SOHO.JK","SONA.JK","SOSS.JK","SOTS.JK"
    ],
    # BATCH 6
    [
        "SOSS.JK","SPMA.JK","SPTO.JK","SQMI.JK","SRAJ.JK","SRIL.JK","SRSN.JK","SRTG.JK","SSIA.JK","SSMS.JK",
        "SSTM.JK","STAR.JK","STTP.JK","SUGI.JK","SULI.JK","SUPR.JK","SURE.JK","SWID.JK","TALF.JK","TAMA.JK",
        "TAMU.JK","TAPG.JK","TARA.JK","TAXI.JK","TBIG.JK","TBLA.JK","TBMS.JK","TCID.JK","TCPI.JK","TDPM.JK",
        "TEBE.JK","TECH.JK","TECT.JK","TELE.JK","TFAS.JK","TFCO.JK","TGKA.JK","TGRA.JK","TIFA.JK","TINS.JK",
        "TIRA.JK","TIRT.JK","TIVA.JK","TKIM.JK","TLKM.JK","TMPO.JK","TMAS.JK","TOTO.JK","TOWR.JK","TOTO.JK",
        "TPEN.JK","TPIA.JK","TPMA.JK","TRAM.JK","TRIO.JK","TRIS.JK","TRST.JK","TRUE.JK","TRUK.JK","TRUS.JK",
        "TSPC.JK","TUGU.JK","TURI.JK","UANG.JK","UCID.JK","UFOE.JK","ULTJ.JK","UNIC.JK","UNIQ.JK","UNIT.JK",
        "UNSP.JK","UNTR.JK","UNVR.JK","URBN.JK","VICI.JK","VINS.JK","VIVA.JK","VOKS.JK","VRNA.JK","WAPO.JK",
        "WEGE.JK","WEHA.JK","WGSH.JK","WICO.JK","WIFI.JK","WIIM.JK","WIKA.JK","WINS.JK","WIRG.JK","WMPP.JK"
    ],
    # BATCH 7
    [
        "WMUU.JK","WOOD.JK","WOWS.JK","WSBP.JK","WSKT.JK","WTON.JK","YELO.JK","YPAS.JK","YULE.JK","ZBRA.JK",
        "ZONE.JK","AALI.JK","ABBA.JK","ACES.JK","ACST.JK","ADES.JK","ADHI.JK","ADMG.JK","ADRO.JK","AGAR.JK",
        "AGII.JK","AKKU.JK","AKPI.JK","AKRA.JK","AKSI.JK","ALDO.JK","ALKA.JK","ALMI.JK","AMAG.JK","AMFG.JK",
        "AMRT.JK","ANDI.JK","ANTM.JK","APEX.JK","APIC.JK","ARCI.JK","ARKA.JK","ARNA.JK","ARTA.JK","ARTI.JK",
        "ASBI.JK","ASDM.JK","ASGR.JK","ASII.JK","ASMI.JK","ASRI.JK","ATIC.JK","AUTO.JK","BABP.JK","BACA.JK",
        "BAJA.JK","BBHI.JK","BBKP.JK","BBMD.JK","BBYB.JK","BCIC.JK","BEBS.JK","BEEF.JK","BELL.JK","BFIN.JK",
        "BHAT.JK","BIMA.JK","BINA.JK","BIPI.JK","BIRD.JK","BJBR.JK","BJTM.JK","BKSL.JK","BMAS.JK","BNBA.JK",
        "BNGA.JK","BOGA.JK","BOLA.JK","BRIS.JK","BRMS.JK","BRPT.JK","BSDE.JK","BSML.JK","BUKA.JK","BULL.JK"
    ],
    # BATCH 8 (sisa saham)
    [
        "BWPT.JK","CAMP.JK","CARE.JK","CASA.JK","CBMF.JK","CEKA.JK","CENT.JK","CFIN.JK","CINT.JK","CLAY.JK",
        "CMNP.JK","CNKO.JK","CNTX.JK","CPIN.JK","COWL.JK","CSAP.JK","CTRA.JK","DART.JK","DEAL.JK","DEFI.JK",
        "DGNS.JK","DIGI.JK","DILD.JK","DKFT.JK","DLTA.JK","DMND.JK","DOID.JK","DPNS.JK","DSFI.JK","DSSA.JK",
        "DUTI.JK","DVLA.JK","DWGL.JK","DYAN.JK","ECII.JK","EKAD.JK","ELSA.JK","ELTY.JK","EMDE.JK","ENRG.JK",
        "ENVY.JK","EPAC.JK","ERAA.JK","ESIP.JK","ESSA.JK","ESTA.JK","ETWA.JK","EXCL.JK","FAST.JK","FASW.JK",
        "FILM.JK","FIRE.JK","FISH.JK","FITT.JK","FMII.JK","FOOD.JK","FORU.JK","FREN.JK","FUJI.JK","GAMA.JK",
        "GDST.JK","GEMA.JK","GEMS.JK","GGRM.JK","GIAA.JK","GJTL.JK","GLOB.JK","GLVA.JK","GMFI.JK","GMTD.JK",
        "GOTO.JK","GPRA.JK","GRHA.JK","GSMF.JK","GTBO.JK","GWSA.JK","HADE.JK","HAIS.JK","HATM.JK","HDTX.JK",
        "HERO.JK","HEXA.JK","HITS.JK","HKMU.JK","HMSP.JK","HOKI.JK","HOME.JK","HOMI.JK","HOTL.JK","HRTA.JK"
    ],
    # BATCH 9 (sisa saham)
    [
        "HRUM.JK","IATA.JK","IBFN.JK","IBST.JK","ICBP.JK","ICON.JK","IDPR.JK","IFII.JK","IFSH.JK","IGAR.JK",
        "IIKP.JK","IKAI.JK","IKAN.JK","IKBI.JK","IMAS.JK","IMPC.JK","INAF.JK","INAI.JK","INCF.JK","INCI.JK",
        "INCO.JK","INDF.JK","INDY.JK","INET.JK","INKP.JK","INOV.JK","INPC.JK","INPP.JK","INPS.JK","INRU.JK",
        "INTA.JK","INTD.JK","INTP.JK","IPCC.JK","IPCM.JK","IPOL.JK","IPTV.JK","IRRA.JK","ISAT.JK","ISSP.JK",
        "ITIC.JK","ITMA.JK","ITMG.JK","JARR.JK","JAST.JK","JAWA.JK","JAYA.JK","JECC.JK","JGLE.JK","JIHD.JK",
        "JKON.JK","JKSW.JK","JMAS.JK","JPFA.JK","JRPT.JK","JSMR.JK","JSPT.JK","JTPE.JK","KAEF.JK","KARW.JK",
        "KAYU.JK","KBAG.JK","KBLI.JK","KBLM.JK","KDSI.JK","KEEN.JK","KEJU.JK","KIJA.JK","KINO.JK","KJEN.JK",
        "KKGI.JK","KLBF.JK","KMDS.JK","KMTR.JK","KOBX.JK","KOIN.JK","KONI.JK","KOPI.JK","KOTA.JK","KPAL.JK",
        "KPAS.JK","KPIG.JK","KRAH.JK","KRAS.JK","KREN.JK","LAND.JK","LAPD.JK","LEAD.JK","LIFE.JK","LINK.JK"
    ],
    # BATCH 10 (sisa saham)
    [
        "LION.JK","LMAS.JK","LMPI.JK","LMSH.JK","LPCK.JK","LPLI.JK","LPKR.JK","LPPF.JK","LRNA.JK","LSIP.JK",
        "LTLS.JK","LUCY.JK","MABA.JK","MAGP.JK","MAIN.JK","MAYA.JK","MBAP.JK","MBSS.JK","MBTO.JK","MCAS.JK",
        "MCOL.JK","MDIA.JK","MDKA.JK","MDLN.JK","MEDC.JK","MEGA.JK","MERK.JK","META.JK","MFMI.JK","MGLV.JK",
        "MGNA.JK","MGRO.JK","MICE.JK","MIDI.JK","MIKA.JK","MINA.JK","MIRA.JK","MITI.JK","MKNT.JK","MKPI.JK",
        "MLBI.JK","MLIA.JK","MLPL.JK","MLPT.JK","MMLP.JK","MNCN.JK","MOLI.JK","MPMX.JK","MPOW.JK","MPPA.JK",
        "MPRO.JK","MRAT.JK","MREI.JK","MSIN.JK","MSKY.JK","MTDL.JK","MTEL.JK","MTFN.JK","MTLA.JK","MTPS.JK",
        "MTRA.JK","MTWI.JK","MYOR.JK","MYRX.JK","MYTX.JK","NASA.JK","NATO.JK","NELY.JK","NFCX.JK","NICK.JK",
        "NIKL.JK","NIPS.JK","NIRO.JK","NISP.JK","NOBU.JK","NPGF.JK","NRCA.JK","NUSA.JK","NZIA.JK","OASA.JK",
        "OCAP.JK","OKAS.JK","OMRE.JK","OPMS.JK","PADI.JK","PALM.JK","PANS.JK","PBRX.JK","PBSA.JK","PCAR.JK"
    ]
]
ISSI_SYMBOLS = [sym for batch in ISSI_BATCHES for sym in batch]
